### ISSUE TITLE
通过将string编译为GBK (ANSI) 的封包来支持中文名

### ISSUE THREAD

**Issue by dounai2333** [KouKouChan/CSO2-Server#1]
这一部分是L-Leite的服务端所没有编写的(所有内容均使用了UTF-8)，由于客户端的关于个人用户的名称封包读取上会默认使用ANSI即简体系统的GBK，因此服务端以UTF-8形式发送给客户端的非ASCII字符会被客户端强制转换导致乱码
**目前客户端仍有一部分有关string的内容仍在使用UTF-8的读取方式，因此可能需要在添加L-Leite的服务端所未拥有的功能时进行详细测试**
目前已知客户端使用UTF-8读取方式的string内容：房间列表(roomlist)内的[房名](https://github.com/L-Leite/cso2-master-server/blob/master/src/packets/out/roomlist/item.ts#L29)和[房主ID](https://github.com/L-Leite/cso2-master-server/blob/master/src/packets/out/roomlist/item.ts#L57)、聊天(chat)的[全部内容](https://github.com/L-Leite/cso2-master-server/tree/master/src/packets/out/chat)

但初次之外的，基本可以通过GBK编码解决乱码问题 (_虽然这会很对不起其他系统例如Big5的繁体等..._)
已知可通过将string编译为GBK封包来避免乱码问题的内容：用户名称、频道名称、战队名称、个性签名等...

由于客户端自身的登录窗口并不支持输入非ASCII字符(会被阻断)，因此需要使用-username及-password启动参数来使用中文名进行登录

**Comment by DanielSimgame** [comment]
我支持了，如果能做出来我一定给很多很好的评价

**Comment by LoveBeforT** [comment]
感谢大佬的提示！我会尽力做的

**Comment by LoveBeforT** [comment]
使用byte数组来储存客户端发来的数据，不对其进行转码，仅对于返回数据包时需要UTF-8编码的数据包进行编码。这样做理论上应该能够支持多种语言

**Comment by dounai2333** [comment]
> 使用byte数组来储存客户端发来的数据，不对其进行转码，仅对于返回数据包时需要UTF-8编码的数据包进行编码。这样做理论上应该能够支持多种语言

客户端传输/接受有关string的字符时 非ASCII字符在多数时候会被编译为UTF8 但在少数时候是以ANSI进行的（N社没指定编码的锅） 这意味着多语言（系统）支持是不可能的，因为服务端可能跟客户端存在编码差异问题 ANSI并不是万能编码 他只是默认选取当前系统下的编码语言而已

编辑: 如果你抱有疑问 可在https://www.107000.com/T-Hex/ 检查GBK和UTF8编码下的非ASCII字符的字节使用区别

已知解决方案：修改区域中“非 Unicode 程序的语言” 修改为"中文 （简体，中国） (即GBK 数字编码936)"即可
![VI112`P698K0O%L~4@ZRV{C](https://user-images.githubusercontent.com/45044404/89101881-b64c5600-d436-11ea-8a29-45e947fff52b.png)

**Comment by KouKouChan** [comment]
> 是的，如果玩家都是一个语言倒是好说，ANSI使用的基本上是同一种编码。多语言系统之间相互通信，即使服务器通过客户端知道对方的编码，也很难实现。

**Comment by LoveBeforT** [comment]
> > 使用byte数组来储存客户端发来的数据，不对其进行转码，仅对于返回数据包时需要UTF-8编码的数据包进行编码。这样做理论上应该能够支持多种语言
> 
> 客户端传输/接受有关string的字符时 非ASCII字符在多数时候会被编译为UTF8 但在少数时候是以ANSI进行的（N社没指定编码的锅） 这意味着多语言（系统）支持是不可能的，因为服务端可能跟客户端存在编码差异问题 ANSI并不是万能编码 他只是默认选取当前系统下的编码语言而已
> 
> 编辑: 如果你抱有疑问 可在https://www.107000.com/T-Hex/ 检查GBK和UTF8编码下的非ASCII字符的字节使用区别
> 
> 已知解决方案：修改区域中“非 Unicode 程序的语言” 修改为"中文 （简体，中国） (即GBK 数字编码936)"即可
> ![VI112`P698K0O%L~4@ZRV{C](https://user-images.githubusercontent.com/45044404/89101881-b64c5600-d436-11ea-8a29-45e947fff52b.png)

是的，如果玩家都是一个语言倒是好说，ANSI使用的基本上是同一种编码。多语言系统之间相互通信，即使服务器通过客户端知道对方的编码，也很难实现。现在主要还是把重心放在拓展功能和测试编码方面
