### ISSUE TITLE
【錯誤回報】關於「經典模式」無法開始

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#10]
![image](https://user-images.githubusercontent.com/10808571/93521849-34bb7380-f963-11ea-816d-c5d5ac649fe7.png)

經過測試後，要把「自動平衡」改成「不使用」才能正常遊戲
如果沒改成不使用就按開始遊戲，會造成：
遊戲無法開始、無法再開房、無法再登入遊戲帳號
（得重啟伺服器才能登入帳號）

**Comment by LoveBeforT** [comment]
下载韩服端链接里的最新汉化包，已解决自动平衡问题

**Comment by bluefatcat1993** [comment]
我無法下載，因為被百度網盤屏蔽了...
能上傳到 Google 雲端硬碟或其他空間嗎？

**Comment by LoveBeforT** [comment]
> 我無法下載，因為被百度網盤屏蔽了...
> 能上傳到 Google 雲端硬碟或其他空間嗎？

好的

**Comment by LoveBeforT** [comment]
已在韩服端下方添加谷歌云链接

**Comment by bluefatcat1993** [comment]
經測試，好像是自動平衡內的【添加電腦】不能使用
