### ISSUE TITLE
why quick start does not work in the latest version running on old server version

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#107]
![image](https://user-images.githubusercontent.com/36341134/100482047-38a80680-3107-11eb-9ab7-81ddddc3709b.png)

running on old server version
when you select a mode, it throws it to the main lobby quick start it closes
quick start only works in 2017
can you support by the server?

Spoiler:
![image](https://user-images.githubusercontent.com/36341134/100482150-83c21980-3107-11eb-83b7-da74e3af8022.png)

**Comment by IGNRexI** [comment]
and new problem 
Client 127.0.0.1:51470 suffered a fault !
runtime error: invalid memory address or nil pointer dereference
Dump data [65 0 34 67 83 79 50 95 85 73 95 81 85 73 67 75 95 83 69 65 82 67 72 95 82 79 79 77 95 84 73 84 76 69 95 48 52 0 0 32 61 99 10 10 0 1 10 0 0 0 0 0 0 0 0 0 0 0] offset: 58
Fault end!

**Comment by LoveBeforT** [comment]
QuickStart is not impletemented

**Comment by IGNRexI** [comment]
Reason: Client Incompatible Or Modified
