### ISSUE TITLE
【給您加油】

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#11]
首先，感謝你開發這個簡單、易於使用的開服程式
讓完全不會 Linux 的我能一鍵開服，真的非常棒

這開服程式讓我能結識更多 CSO2 的遊戲同好，
讓我這個沒有朋友的邊緣人能獲得更多朋友

希望之後，你能繼續保持高的更新頻率，
繼續優化、恢復更多遊戲功能，謝謝！

我也會不時提供建議、回報錯誤...以讓你能看到後，
能有個方向進行製作、優化、新增、除錯

根據之前你的訊息，你剛完成大學期末考
還希望你能以自己生活為主，別讓更新 CSO2-Server 變成你的負擔了

**Comment by bluefatcat1993** [comment]
另外，順便問一下，我每次升級服務端版本時
數據資料 cso2.db 要跟著移除換成新的嗎？

**Comment by LoveBeforT** [comment]
> 另外，順便問一下，我每次升級服務端版本時
> 數據資料 cso2.db 要跟著移除換成新的嗎？

目前0.3.X系列的版本不需要更换数据文件，如果需要更换会说明的
