### ISSUE TITLE
我该怎么使用local-console.bat？

### ISSUE THREAD

**Issue by ysn2382617094wsw** [KouKouChan/CSO2-Server#115]
我该怎么使用local-console.bat给予玩家所有武器或者一些特定的道具，可以麻烦您提供一张物品表或者一些指令么？还有就是在游戏中，频道列表有两个频道，我该怎么更改频道的名字，望解决！谢谢！

**Comment by LoveBeforT** [comment]
开启服务器然后打开bat文件，输入additem + 玩家用户名 + 武器id ，id可以在游戏的cso2_item_rev2.csv文件中找到，更改名字需要自己编译服务器

**Comment by ysn2382617094wsw** [comment]
真的是太感谢了，希望你们越做越好！你们真的棒棒哒~

**Comment by ysn2382617094wsw** [comment]
对了，我想问一下，聊天怎么才能输入中文啊..................

**Comment by LoveBeforT** [comment]
输入中文需要自己破解修改客户端dll文件，或者用国服端

**Comment by ysn2382617094wsw** [comment]
哦，下个国服端看看，我这有个韩服端，然后模式挺多的，就是不能输入中文，呜呜呜呜

**Comment by ysn2382617094wsw** [comment]
对了，那个给予一个人所有物品的指令，应该有吧
GAME_GM_ADD_ALLWEAPONS        = 所有武器已存入你的仓库!

**Comment by LoveBeforT** [comment]
只有GM才能获取所有武器，而且只能给GM自己

**Comment by ysn2382617094wsw** [comment]
大问题，枪可以用箱子开出来，人物呢？？？？？？？？？？我觉得形形色色的女人物可以成为CSO2的一个独特特点
