### ISSUE TITLE
How will we use the new database and what is required?

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#119]
How will we use the new database and what is required?

and i will test html view for verification code

**Comment by LoveBeforT** [comment]
you need install mysql and redis

**Comment by IGNRexI** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/36341134/102501674-be77fb80-408e-11eb-9362-83c67a929b3e.PNG)

**Comment by IGNRexI** [comment]
Is there a connection? I did not understand how to do it

**Comment by IGNRexI** [comment]
![image](https://user-images.githubusercontent.com/36341134/102502325-858c5680-408f-11eb-807a-8986874ec000.png)
 ?

**Comment by IGNRexI** [comment]
Is the json database still available? @KouKouChan

**Comment by LoveBeforT** [comment]
set EnableDatabase=0
