### ISSUE TITLE
【錯誤回報】帳號相關...

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#13]
如果無法正常開始遊戲，關閉遊戲後，無法再次登入帳號

**Comment by bluefatcat1993** [comment]
> 如果無法正常開始遊戲，關閉遊戲後，無法再次登入帳號

補充：得重啟伺服器後，才能再次登入帳號

**Comment by LoveBeforT** [comment]
能描述下问题发生场景吗？

**Comment by bluefatcat1993** [comment]
> 能描述下问题发生场景吗？

例如在房間列表上，點選了無法進入的房間...
