### ISSUE TITLE
怎样添加一个频道虚拟玩家(不是BOT)

### ISSUE THREAD

**Issue by XingPeng-Pixel** [KouKouChan/CSO2-Server#132]
我是一个单机玩家，只能玩竞技模式让我有点无聊，我想玩生化等模式可是**至少要1名玩家以上**，而我只有一个人。
我每次都是进入模式界面然后开控制台**map xxxx**，进入地图后输入bot_add疯狂添加bot，但是**无法结算**和**结束游戏** 
打完之后要重启游戏，否则进不去频道。所以我想是不是有什么办法可以添加一个虚拟玩家**至频道**而非BOT
谢谢您，也很抱歉我提出这个请求.

**Comment by LoveBeforT** [comment]
你好，除了控制台的方法，有以下两个思路：
1.修改游戏CSV文件，使生化模式支持添加bot，或者使用已经魔改好支持添加bot的客户端（有些服的客户端是改好的）
   CSV文件名为custom\scripts\cso2_modlist.csv,使用excel类软件打开修改ui_botmode这项为3
2.一台电脑上同时使用两个客户端，就能正常在房间内进入游戏，然后在游戏内使用控制台命令bot_add添加电脑

**Comment by LoveBeforT** [comment]
如果是使用虚拟玩家，进入游戏后是无法正常开始的，必须要有bot或者普通玩家

**Comment by XingPeng-Pixel** [comment]
嗯，谢谢您,我已经与bot玩上了金猪，生化，大都市等模式
实在是感谢:)

**Comment by merhong2012** [comment]
> 嗯，谢谢您,我已经与bot玩上了金猪，生化，大都市等模式
> 实在是感谢:)

我改了zombie的ui_botmode模式为3，在房间可以添加BOOT了，但是点击开始游戏没反应，请问是什么原因
