### ISSUE TITLE
Can you support dedicated server? (Hosting the Room on the Server

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#133]
Can you support dedicated server? (Hosting the Room on the Server.
some players do not trust VPNs or are trojan and malware conscious.
or how to do it?.

**Comment by LoveBeforT** [comment]
I don't know,and I think official server is also host the room in hoster's PC.

**Comment by IGNRexI** [comment]
If the in-game rooms can be hosted on the host server, this will be a very good improvement!
VPNs are not much preferred
Can we use another ip address instead of 127.0.0.1 and manually edit the ip address of the opened rooms
and there should be such a feature on the server!
and "Can we create a tunnel to connect vds with 2 separate locations" to avoid ping problems?
@KouKouChan

**Comment by izmoxkawaii** [comment]
++++++++++++++++++++++++++++++++++
