### ISSUE TITLE
Server disconnects upon entering the education section

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#134]
Server disconnects upon entering the education section
a new player receives a warning that the server connection has been terminated in the tutorial section
2020/12/30 00:37:56 Sent a server list packet to 78.190.112.203:35778
2020/12/30 00:37:59 User felixabi get achievement campaign id 1
2020/12/30 00:37:59 User felixabi get achievement campaign id 8
2020/12/30 00:37:59 User felixabi get achievement campaign id 16
2020/12/30 00:37:59 User felixabi get achievement campaign id 32
2020/12/30 00:37:59 User felixabi get achievement campaign id 64
Client 78.190.112.203:35778 suffered a fault !
runtime error: index out of range [33] with length 33
Dump data [96 3 128 0] offset: 4
Fault end!

=========================
![image](https://user-images.githubusercontent.com/36341134/103323077-43312500-4a52-11eb-90f8-8224079b870b.png)
=========================

**Comment by IGNRexI** [comment]
and what version does the server work properly? Can you send me a link? (Drive)

**Comment by LoveBeforT** [comment]
It works fine on my PC  ,did you modified the server source code of campaign part ?

**Comment by IGNRexI** [comment]
I use 'AppServer' for multi language
http://45.145.23.31/Main/en-US/Index/
http://45.145.23.31/Main/tr-TR/Index/
http://45.145.23.31/Main/ko-KR/Index/
http://45.145.23.31/Main/zh-CN/Index/
Can you support this within CSO2's own website or something similar
There is a language change in the bottom footer, you can look there.
@KouKouChan
