### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by Mu-Yv** [KouKouChan/CSO2-Server#139]
请问console 总共都有哪些指令呢
(◍•ᴗ•◍)

**Comment by LoveBeforT** [comment]
连接console后能使用的命令都会显示出来，根据提示输入命令即可

**Comment by LoveBeforT** [comment]
![pic](https://user-images.githubusercontent.com/13610008/103449861-3d08a600-4ce9-11eb-9862-337fe21564de.png)

**Comment by Mu-Yv** [comment]
好的谢谢解答(◍•ᴗ•◍)

**Comment by IGNRexI** [comment]
@KouKouChan  Feature Advice About Console
additem @all XXXX
Give items to all registered players
