### ISSUE TITLE
【错误回报】启动器错误

### ISSUE THREAD

**Issue by star-yekong** [KouKouChan/CSO2-Server#14]
1.启动器不会自动读取custom文件夹目录的数据
2.如果使用波浪键控制台输入代码的话会直接闪退

使用的客户端：2017年国服客户端

**Comment by LoveBeforT** [comment]
> 1.启动器不会自动读取custom文件夹目录的数据
> 2.如果使用波浪键控制台输入代码的话会直接闪退
> 
> 使用的客户端：2017年国服客户端

bat文件里添加 -enablecustom 选项

**Comment by star-yekong** [comment]
好的

那使用控制台(波浪键)之后客户端直接闪退，请问是属于启动器本身问题吗？？

还是2017端本身不支持控制台(波浪键)
