### ISSUE TITLE
How do I build CSO2-Server.exe?

### ISSUE THREAD

**Issue by rc0n9027** [KouKouChan/CSO2-Server#142]
help me

**Comment by LoveBeforT** [comment]
Install Golang v1.15.6 and Git and Mingw,then
1. `git clone https://github.com/KouKouChan/CSO2-Server`
2. goto CSO2-Server folder
3. `go build`

**Comment by rc0n9027** [comment]
![캡처](https://user-images.githubusercontent.com/54577916/103498336-ba6a1d00-4e87-11eb-9585-2c868c5618fd.PNG)

There seems to be an error.

**Comment by rc0n9027** [comment]
> Install Golang v1.15.6 and Git and Mingw,then
> 
> 1. `git clone https://github.com/KouKouChan/CSO2-Server`
> 2. goto CSO2-Server folder
> 3. `go build`

thank you
