### ISSUE TITLE
【錯誤回報】遊戲結束後會卡住...

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#15]
![image](https://user-images.githubusercontent.com/10808571/94426442-27528480-01c0-11eb-839c-8f38cf4dd30c.png)
![image](https://user-images.githubusercontent.com/10808571/94426447-2a4d7500-01c0-11eb-982f-89312009f5c9.png)

遊戲結束後，會先卡在圖 1
然後按 esc 退出遊戲後，會卡在圖 2
得把遊戲關掉，重新進入遊戲才行

**Comment by LoveBeforT** [comment]
点击返回大厅没用吗？

**Comment by bluefatcat1993** [comment]
> 点击返回大厅没用吗？

是的，沒有用

**Comment by dounai2333** [comment]
如果房主在使用控制台指令map开地图（即，不使用游戏自带的“开始游戏”按钮）然后正常玩到结算就会100%发生一图的情况，因为服务端判断的是玩家并未开始游戏而是在房间内挂机。
其次，如果房主在游戏中使用Imgui控制台（在最新版已被删除），即使是只是手误打开了1次并且马上关闭也会有超过80%的概率发生这个情况，然后用ESC返回后无法关闭结算窗口，只能重启游戏（参考[(cso2-launcher) Imgui will cause game problems](https://github.com/L-Leite/cso2-launcher/issues/68)）
规避方法：使用已经删除Imgui控制台而转为起源引擎自带控制台的最新版本，或0.2.2（外部窗口的控制台）
‮

然后是小概率由于客户端发送了带有错误识别ID的错误封包导致的服务端判断错误，但这个错误情况概率并不高，且仍然跟控制台有一定关系（根据我的个人测试，错误封包通常在**非房主**在游戏内使用控制台执行特定命令后）

总结：客户端背锅（逃
‮

编辑：如果你在自行编译客户端上有困难，可以使用AppVeyor的工作编译版：
最新版：https://ci.appveyor.com/api/buildjobs/kxgcrwi65skwhmmo/artifacts/build/cso2_launcher-0.6.0-win64_msvc.7z
未修改custom读取规则的新版：https://ci.appveyor.com/api/buildjobs/u978ycm90eqjhhgx/artifacts/build/cso2_launcher-0.6.0-win64_msvc.7z
删除Imgui控制台而启用了起源引擎自带控制台的旧版：https://ci.appveyor.com/api/buildjobs/uku5us6dqy07lfw7/artifacts/build/cso2_launcher-0.6.0-win64_msvc.7z
或0.2.2：https://github.com/L-Leite/cso2-launcher/releases/download/Build-0.2.2-6e7fd504-master/cso2-launcher_0.2.2-master-6e7fd504-Release_binaries.7z

**Comment by bluefatcat1993** [comment]
> 如果房主在使用控制台指令map开地图（即，不使用游戏自带的“开始游戏”按钮）然后正常玩到结算就会100%发生一图的情况，因为服务端判断的是玩家并未开始游戏而是在房间内挂机。
> 其次，如果房主在游戏中使用Imgui控制台（在最新版已被删除），即使是只是手误打开了1次并且马上关闭也会有超过80%的概率发生这个情况，然后用ESC返回后无法关闭结算窗口，只能重启游戏（参考[(cso2-launcher) Imgui will cause game problems](https://github.com/L-Leite/cso2-launcher/issues/68)）
> 规避方法：使用已经删除Imgui控制台而转为起源引擎自带控制台的最新版本，或0.2.2（外部窗口的控制台）
> ‮
> 
> 然后是小概率由于客户端发送了带有错误识别ID的错误封包导致的服务端判断错误，但这个错误情况概率并不高，且仍然跟控制台有一定关系（根据我的个人测试，错误封包通常在**非房主**在游戏内使用控制台执行特定命令后）
> 
> 总结：客户端背锅（逃
> ‮
> 
> 编辑：如果你在自行编译客户端上有困难，可以使用AppVeyor的工作编译版：
> 最新版：https://ci.appveyor.com/api/buildjobs/kxgcrwi65skwhmmo/artifacts/build/cso2_launcher-0.6.0-win64_msvc.7z
> 未修改custom读取规则的新版：https://ci.appveyor.com/api/buildjobs/u978ycm90eqjhhgx/artifacts/build/cso2_launcher-0.6.0-win64_msvc.7z
> 删除Imgui控制台而启用了起源引擎自带控制台的旧版：https://ci.appveyor.com/api/buildjobs/uku5us6dqy07lfw7/artifacts/build/cso2_launcher-0.6.0-win64_msvc.7z
> 或0.2.2：https://github.com/L-Leite/cso2-launcher/releases/download/Build-0.2.2-6e7fd504-master/cso2-launcher_0.2.2-master-6e7fd504-Release_binaries.7z

據知，新版啟動器沒辦法用在 Windows 7 上，不知道 0.6.0 能否用在 Windows 7 上？
