### ISSUE TITLE
亲，我是国内玩家，一直用你的和朋友玩内网单机

### ISSUE THREAD

**Issue by hackxiaonian** [KouKouChan/CSO2-Server#157]
国服客户端怎么反和谐啊？打BOT和玩家都是掉水泥，韩服客户端是可以玩，但是有的物品显示是#CSO2_ITEM_NAME_SET_BLACKMAMBA   这种名字  有几个是  怎么调试回来啊，国服客户端我还没有试用过！

**Comment by LoveBeforT** [comment]
尝试下替换游戏文件，将韩服的掉血文件替换到国服

**Comment by hackxiaonian** [comment]
PKG文件打不开，而且我是小白，还请大佬直接明示，替换那个文件可以反和谐  感恩您！

**Comment by KouKouChan** [comment]
> PKG文件打不开，而且我是小白，还请大佬直接明示，替换那个文件可以反和谐 感恩您！

uncso2，具体文件自己找吧
