### ISSUE TITLE
【問題】要怎麼解鎖？

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#16]
如果將玩家所有槍鎖定，只剩默認武器後，
要怎麼幫玩家針對一些武器進行解鎖？

我在資料庫上看見 Inventorv 這個欄位
但實在看不懂.......

**Comment by LoveBeforT** [comment]
数据库中仓库类型数据储存的是二进制数据，必须先转换出来才能看懂

**Comment by bluefatcat1993** [comment]
> 数据库中仓库类型数据储存的是二进制数据，必须先转换出来才能看懂

要怎麼轉以及怎麼改？

**Comment by LoveBeforT** [comment]
你需要根据源码里面的读取方式自己另写工具

**Comment by LoveBeforT** [comment]
或者等我以后更新json数据库
