### ISSUE TITLE
Can you share the 7.0 server source code? (I wrote from discord)

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#173]
Can you share the 7.0 server source code? (I wrote from discord)
(I'll test the relay system)

**Comment by LoveBeforT** [comment]
It is invalid to modify the server only,you need to modify client launcher

**Comment by LoveBeforT** [comment]
for some reason,I can't public the source code of 0.7.0 , but you can test with 0.5.0 files

**Comment by IGNRexI** [comment]
I solved this problem temporarily with CSO2Launcher
