### ISSUE TITLE
【功能建議】遊戲暱稱和帳號分開

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#18]
在【四、正在编写的功能】中
我注意到了【命令行和数据库(该版本将与旧版本的数据库不兼容！)】

建議於該版本發布時，同時將帳號和暱稱分開
也建議同時支援中文和其他語言的遊戲暱稱

**Comment by LoveBeforT** [comment]
是的，下一个版本更新的地方挺多的，会把账号和游戏内昵称分开的
