### ISSUE TITLE
Thank you and question

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#183]
Thank you for the server support and I am looking forward to the next update.
my members have increased
![image](https://user-images.githubusercontent.com/36341134/113290285-47b1e780-92a6-11eb-9422-143dade28d73.png)
I'll put login form in CSO2Launcher. but how do I connect the entered users to the cso2 database for verification? Is there any sample?
sample:
![44](https://user-images.githubusercontent.com/36341134/113290538-a6776100-92a6-11eb-9eac-6e3af4469c8d.png)

**Comment by LoveBeforT** [comment]
if you enable mysql, you need to connect mysql
