### ISSUE TITLE
如何開啟寶箱時不用鎖匙

### ISSUE THREAD

**Issue by oijai** [KouKouChan/CSO2-Server#184]
如何開啟寶箱時不用鎖匙,
有些寶箱在商城購買後,會提供鎖匙並不會提供寶箱.
有些寶箱購買後並不會提供鎖匙.
有辦法令寶箱開啟不用鎖匙嗎?

**Comment by LoveBeforT** [comment]
客户端最好用世纪天成版本的客户端，韩版进游戏后商城有些物品数据是错误的，服务端现在没有适配韩版。取消钥匙可以修改CSO2-Server/assert/cstrike/scripts/supplyList.csv这个文件，把对应的key改成0

**Comment by oijai** [comment]
如果我把所有鎖匙的都改成0,那麼我在遊戲中就無法再武器箱中看到其他的寶箱這個要如何解決

**Comment by LoveBeforT** [comment]
再描述一下吧，我没看懂，尽量详细

**Comment by oijai** [comment]
我把keyid改成0後
在遊戲的武器箱中看不到任何寶箱
但是我在倉庫是有那個寶箱的存在
這個要如何解決

**Comment by LoveBeforT** [comment]
你确定是改的数据字段吗？不是把keyid这个名字改成0

**Comment by LoveBeforT** [comment]
可能保存后数据结构变了，用excel这些软件应该没问题

**Comment by oijai** [comment]
我明白錯誤的地方了，因為我的電腦是繁體中文系統
直接使用excel打開文件會產生亂碼，儲存的時候會令文件發生錯誤
現在我的問題解決了感謝你的幫忙=]

**Comment by oijai** [comment]
我是用excel
