### ISSUE TITLE
The chat message is not sent after 10 or 15 words.

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#187]
1.For example, we play zombie zeta. and 2 or 3 people are writing at the same time. After 10 to 15 words (spam), the chat is locked. nothing is written...
2.When the user buys 50 or 100 supply and uses the last one, he gets an error and gets stuck in the supply section. needs to restart the game...

and my server has 282 player members .... I hope the server improves a lot.
thanks <3 KouKouChan

**Comment by IGNRexI** [comment]
@KouKouChan a serious mistake

**Comment by LoveBeforT** [comment]
I tried, but this problem not happened
