### ISSUE TITLE
【問題】請問 0.3.11..??

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#19]
內文已更新到 0.3.11
但是發佈還在 0.3.10

**Comment by LoveBeforT** [comment]
因为0.3.11更新了新手教程，但是未更新数据库，所以每次登录都会提示新手教程，我打算在下一次更新数据库后一起发布。
如果想下载0.3.11，可以使用AppVeyor的自动云编译：
![1](https://user-images.githubusercontent.com/13610008/95669669-c65e7f80-0bb5-11eb-96b1-c79395271480.png)
![2](https://user-images.githubusercontent.com/13610008/95669672-cd858d80-0bb5-11eb-8333-9a9a5f1e4f64.png)
![3](https://user-images.githubusercontent.com/13610008/95669675-cf4f5100-0bb5-11eb-8ca2-212ee6b2cd1a.png)
![4](https://user-images.githubusercontent.com/13610008/95669676-d0807e00-0bb5-11eb-9b20-16f5460b948e.png)
