### ISSUE TITLE
【功能建議】E-Mail 帳號數量

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#22]
建議新增【設定每個 E-Mail 能辦幾個遊戲帳號】的功能

因為如果點到無法正常遊玩的房間
就必須等伺服器整個重啟後，才能再登入遊玩…
所以建議可以新增此功能，這樣玩家就能多辦一個或多個帳號來備用

**Comment by LoveBeforT** [comment]
好主意^_^

**Comment by LoveBeforT** [comment]
最新commit里已更新

**Comment by bluefatcat1993** [comment]
下個版本預計什麼時候會發佈？很期待

**Comment by LoveBeforT** [comment]
月底或下个月

**Comment by bluefatcat1993** [comment]
剛剛透過 AppVeyor 下載今天的最新內容，
發現無法連線…於是又切換回之前的版本
