### ISSUE TITLE
【錯誤訊息回報】

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#24]
![image](https://user-images.githubusercontent.com/10808571/97006397-659a5400-1572-11eb-987f-4be838872bed.png)
![image](https://user-images.githubusercontent.com/10808571/97006413-692ddb00-1572-11eb-95b5-f116622d82dd.png)

開始遊戲沒多久後，就出現上圖錯誤訊息
然後就退到桌面了，需重新進入遊戲才行...

以下是我在文字訊息中查看到疑似錯誤訊息
2020/10/23 12:48:33 Error : User coolbar1993 try to start countdown but mode is illegal !
2020/10/23 12:49:24 Error : User coolbar1993 try to toggle but is host !

**Comment by LoveBeforT** [comment]
能进房间游玩吗？

**Comment by LoveBeforT** [comment]
稍后我会更新一个版本

**Comment by LoveBeforT** [comment]
已更新，如果有发生错误，可以直接把服务端提示的错误信息发到issue里

**Comment by bluefatcat1993** [comment]
能進遊戲，只是玩一下後會彈出遊戲並出現圖片中的訊息，晚點我會用您剛發佈的新版本進行測試測試，如有出現錯誤訊息，我會回報上來
