### ISSUE TITLE
錯誤回報

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#26]
錯誤訊息：
2020/10/24 09:35:58 Error : User XXXX try to update a room but isn't host !
2020/10/24 09:56:41 Error : User XXXX try to toggle but is host !

另外，有很多無法正常進入的房間出現在房間列表上
不小心點到的話，就會造成
無法創建房間、無法登入帳號的狀況
然後需要等到伺服器重啟後，才能再登入..

**Comment by LoveBeforT** [comment]
我需要重现该场景，能提供一些方式吗？比如错误的房间由来

**Comment by LoveBeforT** [comment]
找到了一个错误，在修复中

**Comment by bluefatcat1993** [comment]
有玩家是說，在遊戲中玩指令

或是
用其他伺服器的玩家端，開到了加入電腦人的選項
造成房間無法開始以及無法進入該房間以及帳號無法登入

**Comment by LoveBeforT** [comment]
这个问题是客户端一直等待服务器回应数据，然后服务器由于某个原因无法对客户端的请求做出反应，正在修复

**Comment by LoveBeforT** [comment]
已解决
