### ISSUE TITLE
編碼問題

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#27]
server.conf 中的 CodePage 編碼
除了 gbk / big5 外，有 utf8 嗎？

**Comment by LoveBeforT** [comment]
utf8游戏默认就有，不过游戏有些地方的编码使用的不是utf8，而是ansi编码（即和你地区有关的编码），详情可以见 #1

**Comment by LoveBeforT** [comment]
所以需要填写CodePage 来纠正某些场合的乱码问题

**Comment by LoveBeforT** [comment]
CodePage 不仅支持 gbk / big5，还支持很多其他语言的编码，不过我没写在注释里

**Comment by bluefatcat1993** [comment]
我們有幾位玩家，取外文名字
但是顯示不出來，我能設定成 utf8 嗎？

**Comment by LoveBeforT** [comment]
取外文名字，数据库里存的是utf8名字，但是游戏内玩家信息里的名字是ansi编码，服务器传到客户端，客户端只会按照ansi编码来解读这个名字，如果服务器的编码和客户端不一致就会乱码

**Comment by bluefatcat1993** [comment]
所以無解..

**Comment by LoveBeforT** [comment]
是的，除非修改客户端
