### ISSUE TITLE
【錯誤回報】

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#28]
![image](https://user-images.githubusercontent.com/10808571/97180365-ee182f00-17d4-11eb-911c-b746c63ee8d3.png)

有很多幽靈房間，並且無法進入...
不小心點到幽靈房間的話，會...：
1-無法創建房間
2-無法加入其他正常房間
3-無法再登入遊戲

需用管理工具踢掉後
或等伺服器重啟後
才能再正常加入遊戲

**Comment by LoveBeforT** [comment]
你有discord群组吗

**Comment by bluefatcat1993** [comment]
有：https://discord.gg/CBqcPP5

**Comment by LoveBeforT** [comment]
点击某个幽灵房间时，服务器显示的信息能截个图吗？

**Comment by bluefatcat1993** [comment]
我直接邀請通話吧
我分享我畫面給你看
