### ISSUE TITLE
What is the building program?

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#29]
I will make minor changes until the new version is released and what is the build program name?

**Comment by IGNRexI** [comment]
the project is very successful! and when will you make the page and login page for user statistics?

**Comment by IGNRexI** [comment]
can you create config space for the channel and channel requirements can be server.conf - level or clan requirement etc.

**Comment by LoveBeforT** [comment]
you should install  'golang' version 1.14.2 and Git , and then follow these steps:
1. in cmd `go get github.com/KouKouChan/CSO2-Server`
2. you can see project file in your $GOPATH folder 
3.cd $GOPATH\src\github.com\KouKouChan\CSO2-Server
4.in cmd 'go build'
