### ISSUE TITLE
【建議】數據庫能用 MySQL (MariaDB)

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#3]
希望新版本的玩家數據庫能用 MySQL (MariaDB) ...
這樣管理起來比較方便

**Comment by LoveBeforT** [comment]
因为之前有其他项目用的sqlite，所以顺着使用的sqlite，后面会改成mysql这些的

**Comment by LoveBeforT** [comment]
如果想查看数据可以使用SQLiteStudio或者其他sqlite管理软件打开cso2.db文件

**Comment by bluefatcat1993** [comment]
請問您有 QQ 或 Discord 嗎
