### ISSUE TITLE
verification does not send code

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#30]
After entering an e-mail, the page is refreshed but the e-mail was not received.
/register?on_click=sendmail
![image](https://user-images.githubusercontent.com/36341134/97316283-9f24d500-187a-11eb-8ae2-93af246096e6.png)

**Comment by IGNRexI** [comment]
![image](https://user-images.githubusercontent.com/36341134/97318348-d4322700-187c-11eb-9479-8908204d9025.png)
is this you?

**Comment by LoveBeforT** [comment]
> ![image](https://user-images.githubusercontent.com/36341134/97318348-d4322700-187c-11eb-9479-8908204d9025.png)
> is this you?

yeah ^_^

**Comment by LoveBeforT** [comment]
Mail function is defaulted to off，you can enable EnableMail in server.conf ,and set your email smtp server and password
