### ISSUE TITLE
Where is the Channel Name?

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#31]
Where is the Channel Name?
and how to add more channels
Can we adjust the channel requirements?

**Comment by LoveBeforT** [comment]
you can modify channel name in 'CSO2-Server/blademaster/typestruct/servermanager.go' file
`DefalutServerName   = "CSO2-Server[1/1]"`
`DefalutChannelName1 = "CSO2-Channel[1/2]"`
`DefalutChannelName2 = "CSO2-Channel[2/2]"`

and you can add channel in NewMainServer() function which located at 'CSO2-Server/servermanager/servermanager.go' file just like this:

`chl3 := NewChannelInfo([]byte(DefalutChannelName3), chlsrv)`
`if !AddChannel(&chlsrv, &chl3) {`
	`DebugInfo(2, "Error : Unable to initializing main server !")`
	`log.Fatalln("")`
`}`

Then,you need to build the project,and you will get it

**Comment by IGNRexI** [comment]
do some more development for web and set css img js directory by default

**Comment by LoveBeforT** [comment]
> do some more development for web and set css img js directory by default

I'll consider that

**Comment by IGNRexI** [comment]
do php support please i will start using it with wordpress or forum

**Comment by IGNRexI** [comment]
Can you improve the channel list a little more? status. acceptable. big city etc. for

**Comment by IGNRexI** [comment]
https://github.com/izmoxkawaii/CSO2-Server/commit/02479987a99cacf1a97a55d57952702e14091af3
and
https://github.com/izmoxkawaii/CSO2-Server/blob/patch-64/blademaster/typestruct/servermanager.go

are these correct?

**Comment by IGNRexI** [comment]
chlsrv2 := NewChannelServer([]byte(SecondServerName))
	chl13 := NewChannelInfo([]byte(SecondChannelName), chlsrv2)
	if !AddChannel(&chlsrv2, &chl13) {
	DebugInfo(2, "Error : Unable to initializing main server !")
	log.Fatalln("")
	}


servermanager\servermanager.go:29:37: undefined: SecondServerName

when i add new server it gives this error

**Comment by izmoxkawaii** [comment]
package servermanager

import (
	"log"
	"net"
	"sync"

	. "github.com/KouKouChan/CSO2-Server/blademaster/typestruct"
	. "github.com/KouKouChan/CSO2-Server/kerlong"
	. "github.com/KouKouChan/CSO2-Server/verbose"
)

var (
	//MainServer 主服务器
	MainServer = ServerManager{
		0,
		[]*ChannelServer{},
	}
	mainServerMutex sync.Mutex
)

//初始化主服务器，仅运行一次，不考虑互斥问题
func NewMainServer() ServerManager {
	srvmgr := ServerManager{
		0, //初始化，默认数量为0
		[]*ChannelServer{},
	}
	chlsrv1 := NewChannelServer([]byte(FirstServerName))
	chl1 := NewChannelInfo([]byte(FirstChannelName1), chlsrv1)
	if !AddChannel(&chlsrv1, &chl1) ||
		!AddChannelServer(&srvmgr, &chlsrv1) {
		DebugInfo(2, "Error : Unable to initializing main server !")
		log.Fatalln("")
	}
	chl2 := NewChannelInfo([]byte(FirstChannelName2), chlsrv1)
	if !AddChannel(&chlsrv1, &chl2) {
		DebugInfo(2, "Error : Unable to initializing main server !")
		log.Fatalln("")
	}
	
	chl3 := NewChannelInfo([]byte(FirstChannelName3), chlsrv1)
	if !AddChannel(&chlsrv1, &chl3) {
		DebugInfo(2, "Error : Unable to initializing main server !")
		log.Fatalln("")
	}
	
	chl4 := NewChannelInfo([]byte(FirstChannelName4), chlsrv1)
	if !AddChannel(&chlsrv1, &chl4) {
		DebugInfo(2, "Error : Unable to initializing main server !")
		log.Fatalln("")
	}
	
	chl5 := NewChannelInfo([]byte(FirstChannelName5), chlsrv1)
	if !AddChannel(&chlsrv1, &chl5) {
		DebugInfo(2, "Error : Unable to initializing main server !")
		log.Fatalln("")
	}
	
	chl6 := NewChannelInfo([]byte(FirstChannelName6), chlsrv1)
	if !AddChannel(&chlsrv1, &chl6) {
		DebugInfo(2, "Error : Unable to initializing main server !")
		log.Fatalln("")
	}
	
	chl7 := NewChannelInfo([]byte(FirstChannelName7), chlsrv1)
	if !AddChannel(&chlsrv1, &chl7) {
		DebugInfo(2, "Error : Unable to initializing main server !")
		log.Fatalln("")
	}
	
	chl8 := NewChannelInfo([]byte(FirstChannelName8), chlsrv1)
	if !AddChannel(&chlsrv1, &chl8) {
		DebugInfo(2, "Error : Unable to initializing main server !")
		log.Fatalln("")
	}
	
	chl9 := NewChannelInfo([]byte(FirstChannelName9), chlsrv1)
	if !AddChannel(&chlsrv1, &chl9) {
		DebugInfo(2, "Error : Unable to initializing main server !")
		log.Fatalln("")
	}
	
	chl10 := NewChannelInfo([]byte(FirstChannelName10), chlsrv1)
	if !AddChannel(&chlsrv1, &chl10) {
		DebugInfo(2, "Error : Unable to initializing main server !")
		log.Fatalln("")
	}

	chlsrv2 := NewChannelServer([]byte(SecondServerName))
	chl13 := NewChannelInfo([]byte(SecondChannelName), chlsrv2)
	if !AddChannel(&chlsrv2, &chl13) {
	DebugInfo(2, "Error : Unable to initializing main server !")
	log.Fatalln("")
	}

	return srvmgr
}

//主服务器里加频道服务器,一次只能一个协程访问
func AddChannelServer(dest *ServerManager, src *ChannelServer) bool {
	mainServerMutex.Lock()
	defer mainServerMutex.Unlock()
	if dest.ServerNum > MAXSERVERNUM {
		DebugInfo(2, "Error : ChannelServer is too much ! Unable to add more !")
		return false
	}
	if src.ServerIndex == 0 {
		DebugInfo(2, "Error : ID of ChannelServer is illegal !")
		return false
	}
	for _, v := range dest.Servers {
		if v.ServerIndex == src.ServerIndex {
			DebugInfo(2, "Error : ChannelServer is already existed in MainServer!")
			return false
		}
	}
	dest.ServerNum++
	dest.Servers = append(dest.Servers, src)
	return true
}

//新建频道服务器
func NewChannelServer(name []byte) ChannelServer {
	chlsrv := ChannelServer{
		GetNewChannelServerID(),
		3,
		ChannelServerTypeNormal,
		name,
		0,
		[]*ChannelInfo{},
	}
	return chlsrv
}

//频道服务器里加频道,一次只能一个协程访问
func AddChannel(dest *ChannelServer, src *ChannelInfo) bool {
	mainServerMutex.Lock()
	defer mainServerMutex.Unlock()
	if dest.ChannelCount > MAXCHANNELNUM {
		DebugInfo(2, "Error : Channel is too much ! Unable to add more !")
		return false
	}
	if src.ChannelID <= 0 {
		DebugInfo(2, "Error : ID of Channel is illegal !")
		return false
	}
	for _, v := range dest.Channels {
		if v.ChannelID == src.ChannelID {
			DebugInfo(2, "Error : Channel is already existed in ChannelServer!")
			return false
		}
	}
	dest.ChannelCount++
	dest.Channels = append(dest.Channels, src)
	return true
}

//新的频道服务器ID,一次只能一个协程访问
func GetNewChannelServerID() uint8 {
	mainServerMutex.Lock()
	defer mainServerMutex.Unlock()
	if MainServer.ServerNum > MAXSERVERNUM {
		DebugInfo(2, "Error : ChannelServer is too much ! Unable to create more !")
		//ID=0 是非法的
		return 0
	}
	var intbuf [MAXSERVERNUM + 1]uint8
	//哈希思想
	for i := 0; i < int(MainServer.ServerNum); i++ {
		intbuf[MainServer.Servers[i].ServerIndex] = 1
	}
	//找到空闲的ID
	for i := 1; i <= int(MAXSERVERNUM); i++ {
		if intbuf[i] == 0 {
			//找到了空闲ID
			return uint8(i)
		}
	}
	return 0
}

//通过ID得到对应频道服务器
func GetChannelServerWithID(id uint8) *ChannelServer {
	if id <= 0 {
		return nil
	}
	count := MainServer.ServerNum
	for i := 0; i < int(count); i++ {
		if MainServer.Servers[i].ServerIndex == id {
			return MainServer.Servers[i]
		}
	}
	return nil
}

//处理请求服务器列表
func OnServerList(client net.Conn) {
	uPtr := GetUserFromConnection(client)
	if uPtr == nil ||
		uPtr.Userid <= 0 {
		DebugInfo(2, "Error : A unknow Client from", client.RemoteAddr().String(), "request a ChannelList !")
		return
	}
	rst := BuildHeader(uPtr.CurrentSequence, PacketTypeServerList)
	rst = append(rst, MainServer.ServerNum)
	for i := 0; i < int(MainServer.ServerNum); i++ {
		rst = BytesCombine(rst, BuildChannelServerList(*MainServer.Servers[i]))
	}
	SendPacket(rst, uPtr.CurrentConnection)

	uPtr.SetUserChannelServer(0)
	uPtr.QuitChannel()
	DebugInfo(2, "Sent a server list packet to", uPtr.CurrentConnection.RemoteAddr().String())

}

//建立某个频道服务器数据包
func BuildChannelServerList(chlsrv ChannelServer) []byte {
	var list []byte
	l := len(chlsrv.ServerName)
	list = append(list, chlsrv.ServerIndex,
		chlsrv.ServerStatus,
		chlsrv.ServerType,
		uint8(l),
	)
	list = BytesCombine(list, chlsrv.ServerName)
	list = append(list, chlsrv.ChannelCount)
	list = BytesCombine(list, BuildChannelList(chlsrv.ChannelCount, chlsrv.Channels))
	return list
}

func BuildChannelList(num uint8, channels []*ChannelInfo) []byte {
	var list []byte
	for i := 0; i < int(num); i++ {
		temp := make([]byte, 9+len(channels[i].ChannelName))
		offset := 0
		WriteUint8(&temp, channels[i].ChannelID, &offset)
		WriteString(&temp, channels[i].ChannelName, &offset)
		WriteUint16(&temp, channels[i].Unk00, &offset)
		WriteUint16(&temp, channels[i].Unk01, &offset)
		WriteUint8(&temp, channels[i].Unk02, &offset)
		WriteUint8(&temp, channels[i].ChannelType, &offset)
		WriteUint8(&temp, channels[i].ChannelStatus, &offset)
		list = BytesCombine(list, temp[:offset])
	}
	return list
}

**Comment by IGNRexI** [comment]
[servermanager.txt](https://github.com/KouKouChan/CSO2-Server/files/7021879/servermanager.txt)
