### ISSUE TITLE
Can you channel by level? Sample: >A

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#34]
Can you channel by level? Sample: > 

        DefalutServerName   = "Novice Server" or via client .txt #CSO2_NOVICE_CHANNEL_01 = Novice Server
        DefalutServerLevelRequirementMin = 1 // Start
        DefalutServerLevelRequirementMin = 10 // End
        DefalutServerAccessibility = 2    // 1 Yes All   -  2 No Rookie  Player - 3 Clan Member Only - 4 No Entry Permit Test Server
        DefaultServerMessage = Only Novice Players can enter here // Message

        DefalutChannelName1 = "Professional Server" or via client .txt #CSO2_PRO_CHANNEL_01 = Professional Server
        DefalutServer1LevelRequirementMin = 10 // Start
        DefalutServer1LevelRequirementMin = 200 // End
        DefalutServer1Accessibility = 1    //  1 Yes All   -  2 No Rookie  Player - 3 Clan Member Only - 4 No Entry Permit Test Server
        DefaultServer1Message = Only Professional Players can enter here // Message

        DefalutChannelName2 = "Clan Server" // or via client .txt #CSO2_CLAN_CHANNEL_01 = Clan Server
        DefalutServer2LevelRequirementMin = 10 // Start
        DefalutServer2LevelRequirementMin = 100 // End
        DefalutServer2Accessibility = 1    //  1 Yes All   -  2 No Rookie  Player - 3 Clan Member Only - 4 No Entry Permit Test Server
        DefaultServer2Message = Only Clan members can enter here // Message
        Such A Feature Would Be Very Good

**Comment by LoveBeforT** [comment]
this is not nesscary,and will involve a extra workload
