### ISSUE TITLE
docker build 构建后 无法找到 server.conf，item_list.csv。文件路径多了一个 CSO2-Server

### ISSUE THREAD

**Issue by xiaoyun461** [KouKouChan/CSO2-Server#37]
[root@k8s-node2 ~]# git clone https://hub.fastgit.org/KouKouChan/CSO2-Server.git
正克隆到 'CSO2-Server'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 7904 (delta 5), reused 15 (delta 3), pack-reused 7876
接收对象中: 100% (7904/7904), 130.70 MiB | 2.92 MiB/s, done.
处理 delta 中: 100% (1504/1504), done.
[root@k8s-node2 ~]# ls
anaconda-ks.cfg  CSO2-Server
[root@k8s-node2 ~]# cd CSO2-Server/
[root@k8s-node2 CSO2-Server]# docker build -t cso2-server .
Sending build context to Docker daemon  142.8MB
Step 1/10 : FROM golang:1.14.2 as build
 ---> 2421885b04da
Step 2/10 : ENV GO111MODULE on
 ---> Using cache
 ---> 3a89dc0a0dfe
Step 3/10 : ENV GOPROXY=https://goproxy.cn,direct
 ---> Using cache
 ---> 38fa3f410795
Step 4/10 : WORKDIR $GOPATH/src/github.com/KouKouChan/CSO2-Server
 ---> Using cache
 ---> bc7598a82c89
Step 5/10 : ADD . $GOPATH/src/github.com/KouKouChan/CSO2-Server
 ---> Using cache
 ---> bfc777035362
Step 6/10 : COPY ./kerlong $GOPATH/src/github.com/KouKouChan/CSO2-Server/kerlong
 ---> Using cache
 ---> f5260d309f0d
Step 7/10 : RUN go build .
 ---> Using cache
 ---> 9be0264786f5
Step 8/10 : EXPOSE 30001
 ---> Using cache
 ---> 1ca90165b353
Step 9/10 : EXPOSE 30002
 ---> Using cache
 ---> 6442417d0805
Step 10/10 : ENTRYPOINT  ["./CSO2-Server"]
 ---> Using cache
 ---> fdd9f0332ca6
Successfully built fdd9f0332ca6
Successfully tagged cso2-server:latest
[root@k8s-node2 CSO2-Server]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
cso2-server         latest              fdd9f0332ca6        42 seconds ago      1.04GB
golang              1.14.2              2421885b04da        3 months ago        809MB
[root@k8s-node2 CSO2-Server]# docker run -p 30001:30001 -p 30002:30002 cso2-server
Counter-Strike Online 2 Server v0.3.15
Initializing process ...
mkdir1 success!
mkdir2 success!
Reading configure file ...
Loading config file error[open /go/src/github.com/KouKouChan/CSO2-Server\CSO2-Server\configure\server.conf: no such file or directory]
Using default data ...
Reading game data file ...
检测到异常
error: open /go/src/github.com/KouKouChan/CSO2-Server/CSO2-Server/assert/cstrike/scripts/item_list.csv: not a directory
异常结束
[root@k8s-node2 CSO2-Server]#

**Comment by LoveBeforT** [comment]
生成的程序默认认为自己在CSO2-Server文件夹外，所以路径会多一个CSO2-Server，可以尝试移动生成文件

**Comment by LoveBeforT** [comment]
由于项目自0.2.0版本后很久未使用docker，项目自带的dockerfile已经无法正常工作

**Comment by xiaoyun461** [comment]
确实，我在docker hub上看到 最新latest 也是4月前更新的

**Comment by LoveBeforT** [comment]
可以尝试自己编写dockerfile构建或者等待后续更新

**Comment by LoveBeforT** [comment]
fixed
