### ISSUE TITLE
linux 系统下path路径为 双反斜 \\ 不兼容

### ISSUE THREAD

**Issue by xiaoyun461** [KouKouChan/CSO2-Server#38]
main.go 文件中 第141行，142行

> 141 | `DBPath = path + "\\CSO2-Server\\database\\json\\"`
> 142 | `ReportPath = path + "\\CSO2-Server\\database\\report\\"`

### **必须改成 这种 `/` 斜杠 才能被Linux识别**

> **141 | `DBPath = path + "/CSO2-Server/database/json/"`
> 142 | `ReportPath = path + "/CSO2-Server/database/report/"`**

verbose/loger.go 第11行 同理

> 11 |	`file := path + "\\" + name`

configure/configure.go 第 94行 同理

> 94 |	`file := path + "\\CSO2-Server\\configure\\server.conf"`

**Comment by LoveBeforT** [comment]
之前已在feature分支里修复

**Comment by LoveBeforT** [comment]
更新了Dockerfile，现在可以正常使用Docker编译
