### ISSUE TITLE
【問題】要怎麼設定預設的購買清單及人物？

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#4]
我想自行設定每個玩家的預設購買清單及人物等等，要怎麼設定？

**Comment by bluefatcat1993** [comment]
目前已知 buymenu.go / inventory.go / loadout.go.go，但是不知道怎麼輸出成 exe 檔

**Comment by LoveBeforT** [comment]
你是说取消默认拥有所有武器和人物吗？每个仓库物品对应一个ID，这个ID你可以从CSO2解压后的资源文件里面/scripts/cso2_item_rev2.csv找到对应的数据。如果要使用游戏初始武器而不是解锁所有武器你需要修改服务器源码尤其是userlogin.go里面用户登录时调用的仓库数据，我以后会更新自定义仓库武器的功能，这个是在我的项目计划之内的。

**Comment by bluefatcat1993** [comment]
> 你是说取消默认拥有所有武器和人物吗？每个仓库物品对应一个ID，这个ID你可以从CSO2解压后的资源文件里面/scripts/cso2_item_rev2.csv找到对应的数据。如果要使用游戏初始武器而不是解锁所有武器你需要修改服务器源码尤其是userlogin.go里面用户登录时调用的仓库数据，我以后会更新自定义仓库武器的功能，这个是在我的项目计划之内的。

我是指，我想讓玩家進入遊戲後
遊戲購買菜單、人物都是預設的內容

**Comment by LoveBeforT** [comment]
> > 你是说取消默认拥有所有武器和人物吗？每个仓库物品对应一个ID，这个ID你可以从CSO2解压后的资源文件里面/scripts/cso2_item_rev2.csv找到对应的数据。如果要使用游戏初始武器而不是解锁所有武器你需要修改服务器源码尤其是userlogin.go里面用户登录时调用的仓库数据，我以后会更新自定义仓库武器的功能，这个是在我的项目计划之内的。
> 
> 我是指，我想讓玩家進入遊戲後
> 遊戲購買菜單、人物都是預設的內容

那么你需要修改typestruct/inventorygo下的CreateNewUserInventory函数，这个函数实现了用户第一次初始化时的仓库信息，包括购买菜单和使用的人物。

**Comment by bluefatcat1993** [comment]
但我不知道修改後，怎麼輸出成 CSO2-Server.exe 檔案

**Comment by LoveBeforT** [comment]
> 但我不知道修改後，怎麼輸出成 CSO2-Server.exe 檔案

你需要有Golang编译环境，我使用的版本是Go 1.14.2 ， 按照readme里面的方法来。

**Comment by bluefatcat1993** [comment]
我有下載 go 語言了，只是不知道怎麼用...
我安裝 go 語言後，開啟 cmd 輸入 cd C:\CSO2-Server-master
然後輸入 go build 他顯示：
C:\CSO2-Server-master>go build
＃ github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%

**Comment by LoveBeforT** [comment]
这个提示是缺少gcc程序，你可以下载MinGW来安装gcc

**Comment by bluefatcat1993** [comment]
> 这个提示是缺少gcc程序，你可以下载MinGW来安装gcc

能提供下載連結和安裝方式嗎

**Comment by LoveBeforT** [comment]
从官网下载 https://osdn.net/projects/mingw/releases/

**Comment by bluefatcat1993** [comment]
> 从官网下载 https://osdn.net/projects/mingw/releases/

要下載哪一個...?

**Comment by LoveBeforT** [comment]
mingw-get-setup.exe

**Comment by bluefatcat1993** [comment]
> mingw-get-setup.exe

已經安裝好 mingw-get-setup.exe
接下來怎麼操作？

**Comment by LoveBeforT** [comment]
按照提示吧，可以在谷歌或百度里查找到相应教程

**Comment by bluefatcat1993** [comment]
![image](https://user-images.githubusercontent.com/10808571/92941766-5e682c80-f483-11ea-9d72-bbd47bbcb369.png)
不知道怎麼操作....
