### ISSUE TITLE
作者你好，我能發台版端給你嗎...

### ISSUE THREAD

**Issue by bluefatcat1993** [KouKouChan/CSO2-Server#6]
作者你好，我能發台版的端給你嗎？
好想用台版的遊戲端開遊戲…

**Comment by LoveBeforT** [comment]
可以，我会帮你试试

**Comment by bluefatcat1993** [comment]
> 可以，我会帮你试试

下載連結
https://drive.google.com/file/d/1eqPrRO_HecR0g-2Nhko9seSXfLoPszta/view?usp=sharing

再麻煩你試試看了
很想用台版玩家端玩遊戲

**Comment by LoveBeforT** [comment]
新版启动器无法自动找到要修改的内存地址
Err: Failed to find 5 engine.dll addresses
Err: Failed to find 1 shaderapidx9.dll addresses

启动器作者是L-Leite，目前的方案只能是把台服的文件解压后放到韩服下，让韩服客户端加载台服文件

**Comment by bluefatcat1993** [comment]
> 新版启动器无法自动找到要修改的内存地址
> Err: Failed to find 5 engine.dll addresses
> Err: Failed to find 1 shaderapidx9.dll addresses
> 
> 启动器作者是L-Leite，目前的方案只能是把台服的文件解压后放到韩服下，让韩服客户端加载台服文件

那個我有回報BUG，還請檢查一下
