### ISSUE TITLE
I added a new box but it doesn't show up in the grocery store

### ISSUE THREAD

**Issue by IGNRexI** [KouKouChan/CSO2-Server#94]
I added a new box but it doesn't show up in the grocery store
Attached in CSO2 Client

![image](https://user-images.githubusercontent.com/36341134/99600705-07488000-2a0f-11eb-9ffc-74651c7cb845.png)

![image](https://user-images.githubusercontent.com/36341134/99600730-10395180-2a0f-11eb-88d5-99ffbf31a3cc.png)

![image](https://user-images.githubusercontent.com/36341134/99600739-17f8f600-2a0f-11eb-9698-4407ce1fae3d.png)

Where could I have done wrong?

**Comment by LoveBeforT** [comment]
There should be something wrong in client , not in server, and I'm not sure which file it is. For example,if you add itemid 137 which is m3dragon,it also doesn't show up in shop.

**Comment by IGNRexI** [comment]
Is there a client that works fine? I can use it

**Comment by IGNRexI** [comment]
Is there multilingual support for the .golang web?
Multi-language support for site .html files
'Can we connect locales/zh-cn.ini or any other language?

**Comment by IGNRexI** [comment]
I've added too many weapons but the server still can't read!
does not appear when adding store or karambit for example

example: item_list.csv
5998,#CSO2_ITEM_NAME_Crimson_Web,default_knife,crimson_web,item,weapon,knife,,,,,,,,,,,,,,,,,,,
5999,#CSO2_ITEM_NAME_karambit_doppler,default_knife,karambit_doppler,item,weapon,knife,,,,,,,,,,,,,,,,,,,

[cso2_item_rev2.txt](https://github.com/KouKouChan/CSO2-Server/files/5567175/cso2_item_rev2.txt)

shop.csv > does not see others except default
itemid,price,currency
2001,50000,1
2039,50000,1
2040,50000,1
2041,50000,1
2042,50000,1
2043,50000,1
2044,50000,1
5998,20000,1
5999,80000,1
42060,50000,1
50040,50000,1
50013,50000,1
50038,50000,1
50029,50000,1
50034,50000,1
50036,50000,1
50041,50000,1
50001,50000,1
50024,50000,1
50026,50000,1
50033,50000,1
50003,50000,1
50018,50000,1
50031,50000,1
50004,50000,1
50023,50000,1
50039,50000,1
50011,50000,1
50022,50000,1
50017,50000,1
50002,50000,1
50030,50000,1

Tryin 'other new guns, it doesn't work

**Comment by LoveBeforT** [comment]
you need to modify client file
