### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tlsdlftn79** [KouKouChan/CSO2-Server#96]
github.com/djimenez/iconv-go
go\src\github.com\djimenez\iconv-go\converter.go:8:10: fatal error: iconv.h: No such file or directory
    8 | #include <iconv.h>
      |          ^~~~~~~~~
compilation terminated.

**Comment by LoveBeforT** [comment]
Have you ever checked that iconv-go is missing some files or not?

**Comment by tlsdlftn79** [comment]
> Have you ever checked that iconv-go is missing some files or not?

oo  #include <iconv.h>

**Comment by LoveBeforT** [comment]
I don't know why you can't build iconv-go , it works well on my computer

**Comment by tlsdlftn79** [comment]
준비물:tlsdlftn656@gmail.com 으로 보내주면 안되가요

**Comment by tlsdlftn79** [comment]
제가 윈도우10 64비트
